name: Simple Job

on:
  push:
    branches:
      - master

jobs:
  Hello:
    runs-on: ubuntu-18.04
    steps:
      - name: hello world
        run: echo "Hello world"
  
  Test:
    strategy:
      matrix:
        go-version:[1.15.x, 1.16.x]
        os:[ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Install Go 
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Test
          run: go test 