name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go 
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: go test 
  